# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["hrmsk66@gmail.com"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "rust"
manifest_version = 2
name = "ecp-wildcard-redirects-rust"
service_id = "3EuSqKQXlbpjrkyTKpWQg9"

[local_server]
  [local_server.backends]
    [local_server.backends.origin_0]
      url = "https://httpbin.org"

  [local_server.dictionaries]
    [local_server.dictionaries.redirects]
      file = "redirects_escaped.json"
      format = "json"
